**[Problem 1]: Calculating matrix multiplication by hand**

# Matrix Multiplication:

Matrix \( A \):
\
\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix}


Matrix \( B \):
\
\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}

---

## Step-by-Step Calculation

### Row 1 of \( A \) with Columns of \( B \)
1. \( C[1,1] = (-1)(0) + (2)(0) + (3)(2) = 0 + 0 + 6 = 6 \)
2. \( C[1,2] = (-1)(2) + (2)(2) + (3)(9) = -2 + 4 + 27 = 29 \)
3. \( C[1,3] = (-1)(1) + (2)(-8) + (3)(-1) = -1 - 16 - 3 = -20 \)

### Row 2 of \( A \) with Columns of \( B \)
1. \( C[2,1] = (4)(0) + (-5)(0) + (6)(2) = 0 + 0 + 12 = 12 \)
2. \( C[2,2] = (4)(2) + (-5)(2) + (6)(9) = 8 - 10 + 54 = 52 \)
3. \( C[2,3] = (4)(1) + (-5)(-8) + (6)(-1) = 4 + 40 - 6 = 38 \)

### Row 3 of \( A \) with Columns of \( B \)
1. \( C[3,1] = (7)(0) + (8)(0) + (-9)(2) = 0 + 0 - 18 = -18 \)
2. \( C[3,2] = (7)(2) + (8)(2) + (-9)(9) = 14 + 16 - 81 = -51 \)
3. \( C[3,3] = (7)(1) + (8)(-8) + (-9)(-1) = 7 - 64 + 9 = -48 \)

---

## Final Result

The resulting matrix \( C \) is:
\
\begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48
\end{bmatrix}


**[Problem 2]: Calculation using NumPy functions**

In [9]:
import numpy as np

# Define the matrices
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Perform matrix multiplication using np.dot
result_with_dot = np.dot(a_ndarray, b_ndarray)
result_with_dot

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

**[Problem 3]: Implementing calculations for a certain element**

In [8]:
import numpy as np

# Define matrices
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Solve the matrix product using np.matmul
result_with_matmul = np.matmul(a_ndarray, b_ndarray)
result_with_matmul

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**[Problem 4]: Creating a function to perform matrix multiplication**

In [10]:
import numpy as np

# Define matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Initialize an empty result matrix of the same size as the output (3x3)
result = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))

# Perform manual matrix multiplication
for i in range(a_ndarray.shape[0]):  # Iterate over rows of A
    for j in range(b_ndarray.shape[1]):  # Iterate over columns of B
        for k in range(a_ndarray.shape[1]):  # Iterate over elements in the row/column
            result[i, j] += a_ndarray[i, k] * b_ndarray[k, j]

result

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

**[Problem 5]: Evaluating inputs that are not defined**

In [13]:
import numpy as np

def validate_and_multiply(A, B):
    """
    Validates input arrays A and B for matrix multiplication.
    If valid, computes the product. Otherwise, displays an error message.
    """
    # Check if the number of columns in A matches the number of rows in B
    if A.shape[1] != B.shape[0]:
        print("Error: Matrix dimensions do not match for multiplication.")
        print(f"Matrix A dimensions: {A.shape}")
        print(f"Matrix B dimensions: {B.shape}")
        return None  # Return None if validation fails

    # Perform matrix multiplication if valid
    result = np.matmul(A, B)
    return result

# Example matrices
D = np.array([[1, 2], [-3, 4]])
E = np.array([[5, 6, 7], [8, -9, 10]])

# Attempt multiplication
output = validate_and_multiply(D, E)

if output is not None:
    print("Matrix product:")
    print(output)

Matrix product:
[[ 21 -12  27]
 [ 17 -54  19]]


**[Question 6]: Configuration**

In [20]:
import numpy as np

# Define matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculate the product A * B^T
result = np.dot(a_ndarray, b_ndarray.T)
print(result)

[[  7 -20  13]
 [ -4 -58 -43]
 [  7  88  95]]
